import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy | Chatisha',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen pt-32 pb-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-heading font-bold text-white mb-4">Privacy Policy</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: March 2025</p>

        <div className="prose prose-invert max-w-none space-y-8 text-slate-300">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Information We Collect</h2>
            <p>
              When you use Chatisha, we collect information you provide directly — such as your name, email address,
              WhatsApp number, and business details — when you sign up or configure your account. We also collect
              message logs generated by your WhatsApp bot to help you monitor activity.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Provide, operate, and improve the Chatisha service</li>
              <li>Authenticate your account and protect against fraud</li>
              <li>Send you service-related communications</li>
              <li>Respond to your support requests</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Data Storage</h2>
            <p>
              Your data is stored securely on servers located in the European Union or East Africa region.
              WhatsApp session data is stored only as long as needed to maintain your bot connection.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Third-Party Services</h2>
            <p>
              We use Google for authentication and Anthropic's Claude API to power the AI responses in your bot.
              These services have their own privacy policies. We do not sell your data to any third party.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Your Rights</h2>
            <p>
              You may request deletion of your account and all associated data at any time by contacting us.
              We will process deletion requests within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Contact</h2>
            <p>
              For privacy-related questions, reach us at{' '}
              <a href="mailto:business@chatisha.io" className="text-primary-400 hover:text-primary-300">
                business@chatisha.io
              </a>{' '}
              or via our{' '}
              <Link href="/contact" className="text-primary-400 hover:text-primary-300">
                contact page
              </Link>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
